With output port animation on screen
SuperHouse/OXRS-SHA-StateController-ESP32-FW pull request #2
Opened 2021-09-12 17:53 UTC by moinmoin-sh

output port animation is available .
![output_128](https://user-images.githubusercontent.com/53935853/132997493-f5ea5261-dc66-4743-ae1d-b00da48ec674.JPG)
It was challenging to get 128 outputs visible on the screen, but I think it's not too bad.
The small green indicates the ouput is `off `(cold,save) and the larger red indicates `on `(hot, attention). The information is pulled from the outputs of the MCP's and not depending on the mqtt cmnd's. 
Timer and iInterLock are visible nicely without having any relay.
I also tried a first implementation of the mqtt telemetrie temperature

2021-09-13 00:27 UTC, sumnerboy12 commented
This looks really good - just not sure on the colouring scheme. In my mind GREEN means ON, RED means STOP/OFF. But I can see your thinking. I wonder if there is a better way which is clearer to everyone. Grey == OFF and Green == ON seems pretty obvious - but I think you are using grey to indicate a non-existent port? Could we just leave these empty/black?

When you say the timer and interlock is visible can you show an example?

2021-09-13 00:28 UTC, sumnerboy12 requested changes
As per my comment, just think we should try some different colour schemes for the on/off/missing leds.

2021-09-13 10:51 UTC, moinmoin-sh commented
I was looking for 2 colors to better show the difference, so I took the color coding from our local circuit breaker / line protection switches which may not be obvious to everyone. 
Here are 3 different possibilities (out of not countables ..) . I would like to display the not existent ones with a hollow square and show the `off `state with a lighter solid sqare. Which color do you prefer for `on `? (looking at the comparison below I still like the red/green contrast for on/off)

![grafik](https://user-images.githubusercontent.com/53935853/133070891-3968fb83-a764-4ee1-8bd7-e7a0358445db.png)

2021-09-13 11:03 UTC, moinmoin-sh commented
> When you say the timer and interlock is visible can you show an example?

not so much to show. In case of a `Timer `I can just see the output going `off `when the timer elapsed and in case of `Interlock ` I can see on the screen when I set the one channel to `on `the other channel goes automatically `off`. Also the corresponding events are shown on the buttom line of the screen.

2021-09-13 18:21 UTC, sumnerboy12 commented
> I was looking for 2 colors to better show the difference, so I took the color coding from our local circuit breaker / line protection switches which may not be obvious to everyone. 
> Here are 3 different possibilities (out of not countables ..) . I would like to display the not existent ones with a hollow square and show the `off `state with a lighter solid sqare. Which color do you prefer for `on `? (looking at the comparison below I still like the red/green contrast for on/off)
> 
> ![grafik](https://user-images.githubusercontent.com/53935853/133070891-3968fb83-a764-4ee1-8bd7-e7a0358445db.png)
> 
> 
> 

Yeah that looks good, I like the RED is on, GREY is off, hollow is non existent. I just think the red and green is confusing as to what is what. 

Maybe put it to discord to get others opinions?

2021-09-14 17:04 UTC, moinmoin-sh commented
I think I can merge this with option b) enabled ?

2021-09-14 18:04 UTC, sumnerboy12 commented
Yeah I think so!

On Wed, 15 Sep 2021, 05:04 moinmoin-sh, ***@***.***> wrote:

> I think I can merge this with option b) enabled ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/SuperHouse/OXRS-SHA-StateController-ESP32-FW/pull/2#issuecomment-919343796>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABGTR2RD4TCQTVTNYH7D7ZLUB56DDANCNFSM5D4KJWVQ>
> .
>

2021-09-14 18:08 UTC, merged